import os

BOT_TOKEN = os.getenv("BOT_TOKEN")
CHAT_ID = os.getenv("CHAT_ID")
TWELVEDATA_API_KEY = os.getenv("TWELVEDATA_API_KEY")
print("BOT_TOKEN:", BOT_TOKEN)
print("CHAT_ID:", CHAT_ID)
SYMBOL = "XAUUSD"
TIMEFRAME = "15m"

RISK_PERCENT = 1
MIN_CONFIDENCE = 80
